language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
 global:
   - PINS="mirage-time.dev:. mirage-time-lwt.dev:. mirage-time-unix.dev:."
 matrix:
   - OCAML_VERSION=4.04 PACKAGE="mirage-time"
   - OCAML_VERSION=4.04 PACKAGE="mirage-time-lwt"
   - OCAML_VERSION=4.04 PACKAGE="mirage-time-unix"
